language: ruby
rvm:
  - 2.6.3

env:
  - DB=postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libtag1-dev
before_script:
  - createdb gap-intelligence
  - psql -c 'create database gap-intelligence;' -U postgres
  - bundle install
  - rake db:schema:load
  - bundle exec rake test 
